services:
  # Rails(パブリックサービス)
  - type: web
    name: easy-readzy-web
    rootDir: easy_readzy # Railsアプリがあるディレクトリ
    runtime: ruby
    plan: starter

    buildCommand: bundle install && yarn install
    deployScript: bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /up

    envVars:
      # MySQLへの接続情報をプライベートサービスから参照
      - key: DB_HOST
        fromService:
          name: mysql-db
          type: pserv
          property: host # 例: mysql-db
      - key: DB_PORT
        fromService:
          name: mysql-db
          type: pserv
          property: port # 例: 3306
      - key: DB_NAME
        fromService:
          name: mysql-db
          type: pserv
          envVarKey: MYSQL_DATABASE
      - key: DB_USER
        fromService:
          name: mysql-db
          type: pserv
          envVarKey: MYSQL_USER
      - key: DB_PASS
        fromService:
          name: mysql-db
          type: pserv
          envVarKey: MYSQL_PASSWORD

      # master.keyはGitHubと同期させない
      - key: RAILS_MASTER_KEY
        sync: false

  # MySQL(プライベートサービス)
  - type: pserv
    name: mysql-db
    runtime: docker
    repo: https://github.com/render-examples/mysql # Render公式MySQLテンプレ
    branch: master
    plan: starter

    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10

    envVars:
      - key: MYSQL_DATABASE
        value: easy_readzy_production
      - key: MYSQL_USER
        value: easyreadzy
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
